name: Deploy Cloud Website

on:
  push:
    branches: [main]
    paths:
      - "apps/cloud/**"

jobs:
  publish_landing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build and push the image
        run: |
          docker login --username hey-ewan --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/s3ndotxyz/web/cloud:latest
          docker push ghcr.io/s3ndotxyz/web/cloud:latest
        working-directory: ./apps/cloud

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN2 }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to Koyeb
        run: koyeb service redeploy just-genna/cloud

    permissions:
      contents: read
      packages: write
