name: Deploy S3N Website

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"

jobs:
  publish_page:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build and push the image
        run: |
          docker login --username hey-ewan --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/s3ndotxyz/web/web:latest
          docker push ghcr.io/s3ndotxyz/web/web:latest
        working-directory: ./apps/web

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to Koyeb
        run: koyeb service redeploy ashamed-giulietta/s3n-web

    permissions:
      contents: read
      packages: write
